// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: message_game_api.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace LightGame.Protocol {

  /// <summary>Holder for reflection information generated from message_game_api.proto</summary>
  public static partial class MessageGameApiReflection {

    #region Descriptor
    /// <summary>File descriptor for message_game_api.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageGameApiReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZtZXNzYWdlX2dhbWVfYXBpLnByb3RvEhJMaWdodEdhbWUuUHJvdG9jb2wi",
            "RAoIQ29udGFjdHMSEgoKV2VpWGluQ29kZRgBIAEoCRIPCgdRUUdyb3VwGAIg",
            "ASgJEhMKC1dlaVhpbkdyb3VwGAMgASgJIjEKB0MyUzEwMDESEgoKTW9iaWxl",
            "VHlwZRgBIAEoBRISCgpDdXJWZXJzaW9uGAIgASgJIowBCgdTMkMxMDAxEhQK",
            "DFZlcnNpb25Ub3RhbBgBIAEoCRIUCgxWZXJzaW9uUGF0Y2gYAiABKAkSFgoO",
            "SXNBcHBTdG9yZVBhc3MYAyABKAgSDgoGRmlyVXJsGAQgASgJEg4KBkFwa1Vy",
            "bBgFIAEoCRIOCgZEb25hbWUYBiABKAkSDQoFRml4SXAYByABKAkiLwoHQzJT",
            "MTAwMxISCgpNb2JpbGVUeXBlGAEgASgFEhAKCERldmljZUlkGAIgASgJIqAB",
            "CgdTMkMxMDAzEg4KBlVzZXJJZBgBIAEoAxIQCghVc2VyTmFtZRgCIAEoCRIN",
            "CgVUb2tlbhgDIAEoCRIPCgdMb2dpbklQGAogASgJEhEKCUxvZ2luUG9ydBgL",
            "IAEoBRIOCgZHYXRlSVAYDCABKAkSEAoIR2F0ZVBvcnQYDSABKAUSDQoFQXBp",
            "SVAYDiABKAkSDwoHQXBpUG9ydBgPIAEoBWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::LightGame.Protocol.Contacts), global::LightGame.Protocol.Contacts.Parser, new[]{ "WeiXinCode", "QQGroup", "WeiXinGroup" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LightGame.Protocol.C2S1001), global::LightGame.Protocol.C2S1001.Parser, new[]{ "MobileType", "CurVersion" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LightGame.Protocol.S2C1001), global::LightGame.Protocol.S2C1001.Parser, new[]{ "VersionTotal", "VersionPatch", "IsAppStorePass", "FirUrl", "ApkUrl", "Doname", "FixIp" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LightGame.Protocol.C2S1003), global::LightGame.Protocol.C2S1003.Parser, new[]{ "MobileType", "DeviceId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LightGame.Protocol.S2C1003), global::LightGame.Protocol.S2C1003.Parser, new[]{ "UserId", "UserName", "Token", "LoginIP", "LoginPort", "GateIP", "GatePort", "ApiIP", "ApiPort" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///获取配置信息
  /// </summary>
  public sealed partial class Contacts : pb::IMessage<Contacts>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Contacts> _parser = new pb::MessageParser<Contacts>(() => new Contacts());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Contacts> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LightGame.Protocol.MessageGameApiReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Contacts() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Contacts(Contacts other) : this() {
      weiXinCode_ = other.weiXinCode_;
      qQGroup_ = other.qQGroup_;
      weiXinGroup_ = other.weiXinGroup_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Contacts Clone() {
      return new Contacts(this);
    }

    /// <summary>Field number for the "WeiXinCode" field.</summary>
    public const int WeiXinCodeFieldNumber = 1;
    private string weiXinCode_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string WeiXinCode {
      get { return weiXinCode_; }
      set {
        weiXinCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "QQGroup" field.</summary>
    public const int QQGroupFieldNumber = 2;
    private string qQGroup_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string QQGroup {
      get { return qQGroup_; }
      set {
        qQGroup_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "WeiXinGroup" field.</summary>
    public const int WeiXinGroupFieldNumber = 3;
    private string weiXinGroup_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string WeiXinGroup {
      get { return weiXinGroup_; }
      set {
        weiXinGroup_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Contacts);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Contacts other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (WeiXinCode != other.WeiXinCode) return false;
      if (QQGroup != other.QQGroup) return false;
      if (WeiXinGroup != other.WeiXinGroup) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (WeiXinCode.Length != 0) hash ^= WeiXinCode.GetHashCode();
      if (QQGroup.Length != 0) hash ^= QQGroup.GetHashCode();
      if (WeiXinGroup.Length != 0) hash ^= WeiXinGroup.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (WeiXinCode.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(WeiXinCode);
      }
      if (QQGroup.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(QQGroup);
      }
      if (WeiXinGroup.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(WeiXinGroup);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (WeiXinCode.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(WeiXinCode);
      }
      if (QQGroup.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(QQGroup);
      }
      if (WeiXinGroup.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(WeiXinGroup);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (WeiXinCode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(WeiXinCode);
      }
      if (QQGroup.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(QQGroup);
      }
      if (WeiXinGroup.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(WeiXinGroup);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Contacts other) {
      if (other == null) {
        return;
      }
      if (other.WeiXinCode.Length != 0) {
        WeiXinCode = other.WeiXinCode;
      }
      if (other.QQGroup.Length != 0) {
        QQGroup = other.QQGroup;
      }
      if (other.WeiXinGroup.Length != 0) {
        WeiXinGroup = other.WeiXinGroup;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            WeiXinCode = input.ReadString();
            break;
          }
          case 18: {
            QQGroup = input.ReadString();
            break;
          }
          case 26: {
            WeiXinGroup = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            WeiXinCode = input.ReadString();
            break;
          }
          case 18: {
            QQGroup = input.ReadString();
            break;
          }
          case 26: {
            WeiXinGroup = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class C2S1001 : pb::IMessage<C2S1001>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<C2S1001> _parser = new pb::MessageParser<C2S1001>(() => new C2S1001());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<C2S1001> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LightGame.Protocol.MessageGameApiReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C2S1001() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C2S1001(C2S1001 other) : this() {
      mobileType_ = other.mobileType_;
      curVersion_ = other.curVersion_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C2S1001 Clone() {
      return new C2S1001(this);
    }

    /// <summary>Field number for the "MobileType" field.</summary>
    public const int MobileTypeFieldNumber = 1;
    private int mobileType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MobileType {
      get { return mobileType_; }
      set {
        mobileType_ = value;
      }
    }

    /// <summary>Field number for the "CurVersion" field.</summary>
    public const int CurVersionFieldNumber = 2;
    private string curVersion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CurVersion {
      get { return curVersion_; }
      set {
        curVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as C2S1001);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(C2S1001 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MobileType != other.MobileType) return false;
      if (CurVersion != other.CurVersion) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MobileType != 0) hash ^= MobileType.GetHashCode();
      if (CurVersion.Length != 0) hash ^= CurVersion.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MobileType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(MobileType);
      }
      if (CurVersion.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CurVersion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MobileType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(MobileType);
      }
      if (CurVersion.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CurVersion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MobileType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MobileType);
      }
      if (CurVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CurVersion);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(C2S1001 other) {
      if (other == null) {
        return;
      }
      if (other.MobileType != 0) {
        MobileType = other.MobileType;
      }
      if (other.CurVersion.Length != 0) {
        CurVersion = other.CurVersion;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MobileType = input.ReadInt32();
            break;
          }
          case 18: {
            CurVersion = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MobileType = input.ReadInt32();
            break;
          }
          case 18: {
            CurVersion = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class S2C1001 : pb::IMessage<S2C1001>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<S2C1001> _parser = new pb::MessageParser<S2C1001>(() => new S2C1001());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<S2C1001> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LightGame.Protocol.MessageGameApiReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public S2C1001() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public S2C1001(S2C1001 other) : this() {
      versionTotal_ = other.versionTotal_;
      versionPatch_ = other.versionPatch_;
      isAppStorePass_ = other.isAppStorePass_;
      firUrl_ = other.firUrl_;
      apkUrl_ = other.apkUrl_;
      doname_ = other.doname_;
      fixIp_ = other.fixIp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public S2C1001 Clone() {
      return new S2C1001(this);
    }

    /// <summary>Field number for the "VersionTotal" field.</summary>
    public const int VersionTotalFieldNumber = 1;
    private string versionTotal_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string VersionTotal {
      get { return versionTotal_; }
      set {
        versionTotal_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "VersionPatch" field.</summary>
    public const int VersionPatchFieldNumber = 2;
    private string versionPatch_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string VersionPatch {
      get { return versionPatch_; }
      set {
        versionPatch_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "IsAppStorePass" field.</summary>
    public const int IsAppStorePassFieldNumber = 3;
    private bool isAppStorePass_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsAppStorePass {
      get { return isAppStorePass_; }
      set {
        isAppStorePass_ = value;
      }
    }

    /// <summary>Field number for the "FirUrl" field.</summary>
    public const int FirUrlFieldNumber = 4;
    private string firUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FirUrl {
      get { return firUrl_; }
      set {
        firUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ApkUrl" field.</summary>
    public const int ApkUrlFieldNumber = 5;
    private string apkUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ApkUrl {
      get { return apkUrl_; }
      set {
        apkUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Doname" field.</summary>
    public const int DonameFieldNumber = 6;
    private string doname_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Doname {
      get { return doname_; }
      set {
        doname_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "FixIp" field.</summary>
    public const int FixIpFieldNumber = 7;
    private string fixIp_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FixIp {
      get { return fixIp_; }
      set {
        fixIp_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as S2C1001);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(S2C1001 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (VersionTotal != other.VersionTotal) return false;
      if (VersionPatch != other.VersionPatch) return false;
      if (IsAppStorePass != other.IsAppStorePass) return false;
      if (FirUrl != other.FirUrl) return false;
      if (ApkUrl != other.ApkUrl) return false;
      if (Doname != other.Doname) return false;
      if (FixIp != other.FixIp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (VersionTotal.Length != 0) hash ^= VersionTotal.GetHashCode();
      if (VersionPatch.Length != 0) hash ^= VersionPatch.GetHashCode();
      if (IsAppStorePass != false) hash ^= IsAppStorePass.GetHashCode();
      if (FirUrl.Length != 0) hash ^= FirUrl.GetHashCode();
      if (ApkUrl.Length != 0) hash ^= ApkUrl.GetHashCode();
      if (Doname.Length != 0) hash ^= Doname.GetHashCode();
      if (FixIp.Length != 0) hash ^= FixIp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (VersionTotal.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(VersionTotal);
      }
      if (VersionPatch.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(VersionPatch);
      }
      if (IsAppStorePass != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsAppStorePass);
      }
      if (FirUrl.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(FirUrl);
      }
      if (ApkUrl.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ApkUrl);
      }
      if (Doname.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Doname);
      }
      if (FixIp.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(FixIp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (VersionTotal.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(VersionTotal);
      }
      if (VersionPatch.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(VersionPatch);
      }
      if (IsAppStorePass != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsAppStorePass);
      }
      if (FirUrl.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(FirUrl);
      }
      if (ApkUrl.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ApkUrl);
      }
      if (Doname.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Doname);
      }
      if (FixIp.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(FixIp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (VersionTotal.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(VersionTotal);
      }
      if (VersionPatch.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(VersionPatch);
      }
      if (IsAppStorePass != false) {
        size += 1 + 1;
      }
      if (FirUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FirUrl);
      }
      if (ApkUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ApkUrl);
      }
      if (Doname.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Doname);
      }
      if (FixIp.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FixIp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(S2C1001 other) {
      if (other == null) {
        return;
      }
      if (other.VersionTotal.Length != 0) {
        VersionTotal = other.VersionTotal;
      }
      if (other.VersionPatch.Length != 0) {
        VersionPatch = other.VersionPatch;
      }
      if (other.IsAppStorePass != false) {
        IsAppStorePass = other.IsAppStorePass;
      }
      if (other.FirUrl.Length != 0) {
        FirUrl = other.FirUrl;
      }
      if (other.ApkUrl.Length != 0) {
        ApkUrl = other.ApkUrl;
      }
      if (other.Doname.Length != 0) {
        Doname = other.Doname;
      }
      if (other.FixIp.Length != 0) {
        FixIp = other.FixIp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            VersionTotal = input.ReadString();
            break;
          }
          case 18: {
            VersionPatch = input.ReadString();
            break;
          }
          case 24: {
            IsAppStorePass = input.ReadBool();
            break;
          }
          case 34: {
            FirUrl = input.ReadString();
            break;
          }
          case 42: {
            ApkUrl = input.ReadString();
            break;
          }
          case 50: {
            Doname = input.ReadString();
            break;
          }
          case 58: {
            FixIp = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            VersionTotal = input.ReadString();
            break;
          }
          case 18: {
            VersionPatch = input.ReadString();
            break;
          }
          case 24: {
            IsAppStorePass = input.ReadBool();
            break;
          }
          case 34: {
            FirUrl = input.ReadString();
            break;
          }
          case 42: {
            ApkUrl = input.ReadString();
            break;
          }
          case 50: {
            Doname = input.ReadString();
            break;
          }
          case 58: {
            FixIp = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///游客登录
  /// </summary>
  public sealed partial class C2S1003 : pb::IMessage<C2S1003>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<C2S1003> _parser = new pb::MessageParser<C2S1003>(() => new C2S1003());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<C2S1003> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LightGame.Protocol.MessageGameApiReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C2S1003() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C2S1003(C2S1003 other) : this() {
      mobileType_ = other.mobileType_;
      deviceId_ = other.deviceId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public C2S1003 Clone() {
      return new C2S1003(this);
    }

    /// <summary>Field number for the "MobileType" field.</summary>
    public const int MobileTypeFieldNumber = 1;
    private int mobileType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MobileType {
      get { return mobileType_; }
      set {
        mobileType_ = value;
      }
    }

    /// <summary>Field number for the "DeviceId" field.</summary>
    public const int DeviceIdFieldNumber = 2;
    private string deviceId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DeviceId {
      get { return deviceId_; }
      set {
        deviceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as C2S1003);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(C2S1003 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MobileType != other.MobileType) return false;
      if (DeviceId != other.DeviceId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MobileType != 0) hash ^= MobileType.GetHashCode();
      if (DeviceId.Length != 0) hash ^= DeviceId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MobileType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(MobileType);
      }
      if (DeviceId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DeviceId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MobileType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(MobileType);
      }
      if (DeviceId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DeviceId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MobileType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MobileType);
      }
      if (DeviceId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DeviceId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(C2S1003 other) {
      if (other == null) {
        return;
      }
      if (other.MobileType != 0) {
        MobileType = other.MobileType;
      }
      if (other.DeviceId.Length != 0) {
        DeviceId = other.DeviceId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MobileType = input.ReadInt32();
            break;
          }
          case 18: {
            DeviceId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MobileType = input.ReadInt32();
            break;
          }
          case 18: {
            DeviceId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class S2C1003 : pb::IMessage<S2C1003>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<S2C1003> _parser = new pb::MessageParser<S2C1003>(() => new S2C1003());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<S2C1003> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LightGame.Protocol.MessageGameApiReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public S2C1003() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public S2C1003(S2C1003 other) : this() {
      userId_ = other.userId_;
      userName_ = other.userName_;
      token_ = other.token_;
      loginIP_ = other.loginIP_;
      loginPort_ = other.loginPort_;
      gateIP_ = other.gateIP_;
      gatePort_ = other.gatePort_;
      apiIP_ = other.apiIP_;
      apiPort_ = other.apiPort_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public S2C1003 Clone() {
      return new S2C1003(this);
    }

    /// <summary>Field number for the "UserId" field.</summary>
    public const int UserIdFieldNumber = 1;
    private long userId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long UserId {
      get { return userId_; }
      set {
        userId_ = value;
      }
    }

    /// <summary>Field number for the "UserName" field.</summary>
    public const int UserNameFieldNumber = 2;
    private string userName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserName {
      get { return userName_; }
      set {
        userName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Token" field.</summary>
    public const int TokenFieldNumber = 3;
    private string token_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Token {
      get { return token_; }
      set {
        token_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "LoginIP" field.</summary>
    public const int LoginIPFieldNumber = 10;
    private string loginIP_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LoginIP {
      get { return loginIP_; }
      set {
        loginIP_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "LoginPort" field.</summary>
    public const int LoginPortFieldNumber = 11;
    private int loginPort_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int LoginPort {
      get { return loginPort_; }
      set {
        loginPort_ = value;
      }
    }

    /// <summary>Field number for the "GateIP" field.</summary>
    public const int GateIPFieldNumber = 12;
    private string gateIP_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GateIP {
      get { return gateIP_; }
      set {
        gateIP_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "GatePort" field.</summary>
    public const int GatePortFieldNumber = 13;
    private int gatePort_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int GatePort {
      get { return gatePort_; }
      set {
        gatePort_ = value;
      }
    }

    /// <summary>Field number for the "ApiIP" field.</summary>
    public const int ApiIPFieldNumber = 14;
    private string apiIP_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ApiIP {
      get { return apiIP_; }
      set {
        apiIP_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ApiPort" field.</summary>
    public const int ApiPortFieldNumber = 15;
    private int apiPort_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ApiPort {
      get { return apiPort_; }
      set {
        apiPort_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as S2C1003);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(S2C1003 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserId != other.UserId) return false;
      if (UserName != other.UserName) return false;
      if (Token != other.Token) return false;
      if (LoginIP != other.LoginIP) return false;
      if (LoginPort != other.LoginPort) return false;
      if (GateIP != other.GateIP) return false;
      if (GatePort != other.GatePort) return false;
      if (ApiIP != other.ApiIP) return false;
      if (ApiPort != other.ApiPort) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UserId != 0L) hash ^= UserId.GetHashCode();
      if (UserName.Length != 0) hash ^= UserName.GetHashCode();
      if (Token.Length != 0) hash ^= Token.GetHashCode();
      if (LoginIP.Length != 0) hash ^= LoginIP.GetHashCode();
      if (LoginPort != 0) hash ^= LoginPort.GetHashCode();
      if (GateIP.Length != 0) hash ^= GateIP.GetHashCode();
      if (GatePort != 0) hash ^= GatePort.GetHashCode();
      if (ApiIP.Length != 0) hash ^= ApiIP.GetHashCode();
      if (ApiPort != 0) hash ^= ApiPort.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UserId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(UserId);
      }
      if (UserName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(UserName);
      }
      if (Token.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Token);
      }
      if (LoginIP.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(LoginIP);
      }
      if (LoginPort != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(LoginPort);
      }
      if (GateIP.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(GateIP);
      }
      if (GatePort != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(GatePort);
      }
      if (ApiIP.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(ApiIP);
      }
      if (ApiPort != 0) {
        output.WriteRawTag(120);
        output.WriteInt32(ApiPort);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UserId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(UserId);
      }
      if (UserName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(UserName);
      }
      if (Token.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Token);
      }
      if (LoginIP.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(LoginIP);
      }
      if (LoginPort != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(LoginPort);
      }
      if (GateIP.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(GateIP);
      }
      if (GatePort != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(GatePort);
      }
      if (ApiIP.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(ApiIP);
      }
      if (ApiPort != 0) {
        output.WriteRawTag(120);
        output.WriteInt32(ApiPort);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UserId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(UserId);
      }
      if (UserName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserName);
      }
      if (Token.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Token);
      }
      if (LoginIP.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LoginIP);
      }
      if (LoginPort != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LoginPort);
      }
      if (GateIP.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GateIP);
      }
      if (GatePort != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GatePort);
      }
      if (ApiIP.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ApiIP);
      }
      if (ApiPort != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ApiPort);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(S2C1003 other) {
      if (other == null) {
        return;
      }
      if (other.UserId != 0L) {
        UserId = other.UserId;
      }
      if (other.UserName.Length != 0) {
        UserName = other.UserName;
      }
      if (other.Token.Length != 0) {
        Token = other.Token;
      }
      if (other.LoginIP.Length != 0) {
        LoginIP = other.LoginIP;
      }
      if (other.LoginPort != 0) {
        LoginPort = other.LoginPort;
      }
      if (other.GateIP.Length != 0) {
        GateIP = other.GateIP;
      }
      if (other.GatePort != 0) {
        GatePort = other.GatePort;
      }
      if (other.ApiIP.Length != 0) {
        ApiIP = other.ApiIP;
      }
      if (other.ApiPort != 0) {
        ApiPort = other.ApiPort;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            UserId = input.ReadInt64();
            break;
          }
          case 18: {
            UserName = input.ReadString();
            break;
          }
          case 26: {
            Token = input.ReadString();
            break;
          }
          case 82: {
            LoginIP = input.ReadString();
            break;
          }
          case 88: {
            LoginPort = input.ReadInt32();
            break;
          }
          case 98: {
            GateIP = input.ReadString();
            break;
          }
          case 104: {
            GatePort = input.ReadInt32();
            break;
          }
          case 114: {
            ApiIP = input.ReadString();
            break;
          }
          case 120: {
            ApiPort = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            UserId = input.ReadInt64();
            break;
          }
          case 18: {
            UserName = input.ReadString();
            break;
          }
          case 26: {
            Token = input.ReadString();
            break;
          }
          case 82: {
            LoginIP = input.ReadString();
            break;
          }
          case 88: {
            LoginPort = input.ReadInt32();
            break;
          }
          case 98: {
            GateIP = input.ReadString();
            break;
          }
          case 104: {
            GatePort = input.ReadInt32();
            break;
          }
          case 114: {
            ApiIP = input.ReadString();
            break;
          }
          case 120: {
            ApiPort = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
